name: demo
on: push
jobs:
 job1:
   runs-on: ubuntu-latest
   steps:
     - name: display the echo command
       run:this is sample one\
  example_matrix:
    runs-on: ubuntu-latest
    strategy: 
      version: [10, 12, 14]

